### ISSUE TITLE
Add subcategories so that can be used for marketplace

### ISSUE THREAD

**Issue by zbaloch** [mudzikalfahri/wefootwear-ecommerce#1]
Hi Mudzil,

First of thank you for making this opensource. This is super useful store and easily can be used as full fledged store. It would be great if you can extend this to make a little more like a marketplace so that it can be used as a marketplace as well.

Best,
Zaheer

**Comment by mudzikalfahri** [comment]
hi zaheer, thanks for giving the advice about the project i made, i really appreciate it. Yes, maybe in the near future more features such as detailed categories, sorting and filters will be added to find the product that you want.

**Comment by zbaloch** [comment]
Much appreciated, and let me tell you this too that its super awesome UI that you made there. I would buy the products just because of the store the way it works!!!
