### ISSUE TITLE
View backend Strapi

### ISSUE THREAD

**Issue by stvgale** [mudzikalfahri/wefootwear-ecommerce#2]
Hi, this project is great.  Is there any way I can access the Strapi backend to take a look at structure? Thanks!

**Comment by mudzikalfahri** [comment]
sure, you can access the strapi via this link https://wefootwear-api.herokuapp.com/admin then enter user@wefootwear.com and User12345 for the password

**Comment by stvgale** [comment]
Thanks for sharing this.  Do you have any documentation on how Firebase was
set up?

**Comment by HeDevedUp** [comment]
hey Muzik
these your project really inspired me thanks a lot again
hey how did you connect to strapi
