### ISSUE TITLE
hey 

### ISSUE THREAD

**Issue by chitrakshbotwala** [mudzikalfahri/wefootwear-ecommerce#9]
hey mudzikalfarhi i just wanted to use this project for some personal ecommerce selling could you help me out wwith some stuff please and do i have youre consent to use this

**Comment by mudzikalfahri** [comment]
You can just clone it and use the layout or whatever you want. but sorry I can't help you because I don't touch this project anymore

**Comment by chitrakshbotwala** [comment]
Hey Mudzik , i just wanted to know what the HOST in env variable stands for
and what is the stripe signing secret and where to find it , It would be
nice if you can tell me

**Comment by chitrakshbotwala** [comment]
it also given an issue while building it on vercel deploy (hosting)

**Comment by chitrakshbotwala** [comment]
Hello mudzikalfahri I just wanted to know what the env variables in you're
we foot wear store mean if you could specify what they mean and where to
find them it would be a great help.

Kind regards
Chitraksh Maheshwari

**Comment by mudzikalfahri** [comment]
the HOST is the domain name you want to deploy. if you just run it locally, you can fill it with http://localhost:3000. there's also NEXT_PUBLIC_APIURL which must be filled with the API of the app (mine is https://wefootwear-api.herokuapp.com). i recommend you to install your own nextjs project and API then just use this project as the styles or UI reference. Thank you

**Comment by chitrakshbotwala** [comment]
Will do, thanks! For the information and very sorry to bother you again and
again.

Kind regards
Chitraksh Maheshwari
